#!/bin/bash
# Copyright 2025 © Astitv Singh <https://github.com/astitvsingh>.
# SPDX-License-Identifier: GPL-3.0

# USAGE:
# This script sets up GitHub CLI (`gh`) with full scope access for a repository.
#
# Run this script with:
# bash ./.github/gh/setup
#
# Prerequisites:
# - Ensure GitHub CLI (`gh`) is installed on your system.
# - You must have access to the GitHub account you wish to authenticate.
# - The script should be executed from the repository root directory.

# Ensure the script exits on errors
set -e

# Authenticate GitHub CLI
echo -e "\n🔐  GitHub CLI Setup Task [1/2]: Authentication"
bash ./.github/gh/auth

# Create labels
echo -e "\n🏷️  GitHub CLI Setup Task [2/2]: Creating Labels"
bash ./.github/gh/createLabels

# # Create workflows
# echo -e "\n🔄  GitHub CLI Setup Task [3/3]: Creating Workflows"
# bash ./.github/gh/createWorkflows
